In [66]:
import numpy as np

In [67]:
def get_S(A):
    N = len(A[0])
    S = np.zeros(N)
    for i in range(1, N):
        S[i] = np.sum(A[i])
    print('S', S)
    return S

In [68]:
def get_SS(A):
    N = len(A[0])
    SS = np.zeros(N)
    for i in range(1, N):
        for j in range(1, N):
            if A[i][j] != 0:
                SS[i] += j + 1 #так как нумерация идёт с нуля, прибавим единичку к индексу
    print('SS', SS)
    return SS

In [69]:
def find_max_SS(A, S, SS):
    N = len(A[0])
    k = [0] #индексы максимальных элементов SS
    for i in range(1, N):
        if SS[i] > SS[k[0]]:
            k = np.array([i])
        elif SS[i] == SS[k[0]] and i != 0:
            k = np.append(k, i)
    if len(k) == 1:
        return k[0]
    m = k[0] #индекс SS, у которого меньше всего слагаемых
    for i in k:
        if S[m] < S[i]:
            m = i
        elif S[m] == S[i] and i != k[0]: #число слагаемых оказалось равно
            for j in range(N):
                if A[i][j] or A[m][j]:
                    if A[i][j] < A[m][j]:
                        m = i
                        break
    return m

In [70]:
# зададим матрицу смежности графа
N = 15
A = np.random.randint(2, size=(N, N))
# делаем матрицу симметричной
A = np.tril(A) + np.tril(A, -1).T
for i in range(N):
    A[i][i] = 0
#print(A)
b = np.linspace(1, N, N, endpoint=True)
A = np.append(b[:,np.newaxis], A, axis=1)
#print(A)
b = np.linspace(0, N, N+1, endpoint=True)
A = np.append(b[np.newaxis,:], A, axis=0)
print(A)
print(A[1:, 1:])

[[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.
   14.  15.]
 [  1.   0.   1.   1.   1.   1.   0.   1.   0.   0.   0.   1.   0.   0.
    0.   0.]
 [  2.   1.   0.   0.   1.   1.   1.   0.   1.   1.   0.   1.   1.   0.
    1.   0.]
 [  3.   1.   0.   0.   1.   0.   1.   1.   0.   0.   0.   1.   0.   0.
    1.   1.]
 [  4.   1.   1.   1.   0.   1.   0.   1.   0.   0.   1.   0.   0.   1.
    1.   1.]
 [  5.   1.   1.   0.   1.   0.   0.   0.   0.   0.   0.   0.   0.   1.
    1.   0.]
 [  6.   0.   1.   1.   0.   0.   0.   1.   1.   1.   0.   0.   1.   1.
    1.   0.]
 [  7.   1.   0.   1.   1.   0.   1.   0.   1.   1.   0.   0.   1.   1.
    1.   1.]
 [  8.   0.   1.   0.   0.   0.   1.   1.   0.   1.   1.   0.   0.   0.
    0.   0.]
 [  9.   0.   1.   0.   0.   0.   1.   1.   1.   0.   0.   1.   1.   1.
    0.   1.]
 [ 10.   0.   0.   0.   1.   0.   0.   0.   1.   0.   0.   1.   1.   0.
    0.   1.]
 [ 11.   1.   1.   1.   0.   0.   0.   0.   0.   1.   1.   0.   1

In [71]:
def MW_Alg(A):
    A_init = A
    
    while np.count_nonzero(A[1:, 1:]):
        S = get_S(A)
        SS = get_SS(A)
        m = find_max_SS(A, S, SS)
        print('нужная вершина', m)
        N = len(A[0])
        to_remove = np.zeros(0)
        to_remove_index = np.zeros(0)
        for i in range(1, N):
            if A[m][i] == 1:
                to_remove = np.append(to_remove, i)
                to_remove_index = np.append(to_remove_index, A[i][0])
        print('инцидентные к ней вершины', to_remove_index)

        for i in sorted(to_remove, reverse=True): 
            A = np.delete(A, i, 0)
            A = np.delete(A, i, 1)
        print('\nновая матрица\n', A)
        
    for i in sorted(A[0, 1:], reverse=True): 
        A_init = np.delete(A_init, i, 0)
        A_init = np.delete(A_init, i, 1)
    print(A_init)

In [72]:
MW_Alg(A)

S [  0.   7.  11.  10.  13.  10.  14.  17.  13.  17.  15.  19.  19.  20.  23.
  24.]
SS [  0.  38.  79.  65.  79.  39.  76.  95.  39.  82.  55.  74.  67.  67.  75.
  92.]
нужная вершина 7
инцидентные к ней вершины [  1.   3.   4.   6.   8.   9.  12.  13.  14.  15.]

новая матрица
 [[  0.   2.   5.   7.  10.  11.]
 [  2.   0.   1.   0.   0.   1.]
 [  5.   1.   0.   0.   0.   0.]
 [  7.   0.   0.   0.   0.   0.]
 [ 10.   0.   0.   0.   0.   1.]
 [ 11.   1.   0.   0.   1.   0.]]
S [  0.   4.   6.   7.  11.  13.]
SS [ 0.  9.  2.  0.  6.  7.]
нужная вершина 1
инцидентные к ней вершины [  5.  11.]

новая матрица
 [[  0.   2.   7.  10.]
 [  2.   0.   0.   0.]
 [  7.   0.   0.   0.]
 [ 10.   0.   0.   0.]]
[[  0.   1.   3.   4.   5.   6.   8.   9.  11.  12.  13.  14.  15.]
 [  1.   0.   1.   1.   1.   0.   0.   0.   1.   0.   0.   0.   0.]
 [  3.   1.   0.   1.   0.   1.   0.   0.   1.   0.   0.   1.   1.]
 [  4.   1.   1.   0.   1.   0.   0.   0.   0.   0.   1.   1.   1.]
 [  5.   1.   0.   1

/usr/local/lib/python3.5/dist-packages/ipykernel/__main__.py:19: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future
/usr/local/lib/python3.5/dist-packages/ipykernel/__main__.py:20: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future
/usr/local/lib/python3.5/dist-packages/ipykernel/__main__.py:24: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future
/usr/local/lib/python3.5/dist-packages/ipykernel/__main__.py:25: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future
